package boot

import (
	"crypto/sha256"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

const (
	DefaultESP  = "/boot"
	EFILinuxDir = "EFI/Linux"
	AddonsDir   = "EFI/Linux/addons"
)

// BaseUKI represents a UKI .efi file placed by dracut on the ESP.
type BaseUKI struct {
	Path   string // absolute path
	Name   string // filename without directory
	SHA256 string
}

// FindBaseUKIs scans ESP/EFI/Linux/ for .efi files NOT generated by snapboot.
func FindBaseUKIs(esp string) ([]BaseUKI, error) {
	dir := filepath.Join(esp, EFILinuxDir)
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("cannot read %s: %w", dir, err)
	}

	var ukis []BaseUKI
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		// Skip addon files we generated ourselves.
		if strings.HasPrefix(name, "snapboot-") {
			continue
		}
		if !strings.HasSuffix(name, ".efi") {
			continue
		}
		abs := filepath.Join(dir, name)
		hash, err := sha256File(abs)
		if err != nil {
			return nil, err
		}
		ukis = append(ukis, BaseUKI{Path: abs, Name: name, SHA256: hash})
	}
	return ukis, nil
}

// LatestBaseUKI returns the most recently modified base UKI found on the ESP.
// dracut typically produces one active UKI; this handles multi-kernel setups.
func LatestBaseUKI(esp string) (*BaseUKI, error) {
	ukis, err := FindBaseUKIs(esp)
	if err != nil {
		return nil, err
	}
	if len(ukis) == 0 {
		return nil, fmt.Errorf("no base UKI .efi files found in %s", filepath.Join(esp, EFILinuxDir))
	}
	var best *BaseUKI
	var bestTime int64
	for i := range ukis {
		info, err := os.Stat(ukis[i].Path)
		if err != nil {
			continue
		}
		if info.ModTime().Unix() > bestTime {
			bestTime = info.ModTime().Unix()
			best = &ukis[i]
		}
	}
	return best, nil
}

// AddonDir returns the absolute path to the addons directory on the ESP.
func AddonDir(esp string) string {
	return filepath.Join(esp, AddonsDir)
}

// AddonPath returns where snapboot places the addon .efi for a given snapshot ID.
func AddonPath(esp string, snapshotID int) string {
	return filepath.Join(AddonDir(esp), fmt.Sprintf("snapboot-%d.efi", snapshotID))
}

// EnsureAddonDir creates the addons directory if it doesn't exist.
func EnsureAddonDir(esp string) error {
	return os.MkdirAll(AddonDir(esp), 0755)
}

// SHA256File returns the hex SHA256 digest of a file.
func sha256File(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer f.Close()
	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return "", err
	}
	return fmt.Sprintf("%x", h.Sum(nil)), nil
}

// SHA256String returns the hex SHA256 digest of a string.
func SHA256String(s string) string {
	h := sha256.Sum256([]byte(s))
	return fmt.Sprintf("%x", h)
}
